[project]
name = "psql-update"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ichikawa" }
]
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.1",
]
